version: "3.0"

services:
  image-resizer:
    build: 
      context: .
    env_file: .env
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
      - "9229:9229"
    command: npm run dev
